import { Poppins, Roboto } from "next/font/google";
import "./globals.css";

const roboto = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.className}`}>
      <body>{children}</body>
    </html>
  );
}
